# run_python_script.yml
---
- name: Run Python Script
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Python script
      ansible.builtin.command:
        cmd: python3 hello_world.py
