# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy the local script to the container
COPY hello_script.py .

# Run the script
CMD ["python", "./hello_script.py"]