---
- name: Automate Tasks
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Read the Excel File
      command: python3 ../scripts/read_excel.py 
      register: excel_output
      ignore_errors: yes

    - name: Print the result of reading the Excel file
      debug:
        var: excel_output.stdout_lines

    - name: Generate a Configuration File
      command: python3 ../scripts/generate_config.py
      when: excel_output is succeeded
      register: config_status
      ignore_errors: yes

    - name: Print the result of reading the Excel file
      debug:
        var: config_status.stdout_lines

    - name: Run Docker Compose
      command: docker-compose -f composetest/docker-compose.yml up -d
      when: config_status is succeeded
      ignore_errors: yes

    # - name: Handle Failure
    #   debug:
    #     msg: "An error occurred during the process."
    #   when: excel_output.failed or config_status.failed
