
[agent]
service = "troescorp_modbus"
simulation = false
interval_in_miliseconds = 500
log_level = "info"
log_mode = "console"

[inputs]

[[inputs.tcp]]
name = "BAMS"
controller = "192.168.2.73:503"
slave_id = 2
input_registers = [
  # * Serial Block 1 Started
  { name = "bams_soc", source = 100, target = 100 },
  { name = "bams_soh", source = 101, target = 101 },
  { name = "bams_temporary_power", source = 199, target = 998 },
  { name = "bams_voltage_1", source = 104, target = 104 },
  { name = "bams_voltage_2", source = 105, target = 105 },
  { name = "bams_temporary_current", source = 200, target = 999 },
  { name = "maximum_cell_voltage", source = 108, target = 108 },
  { name = "minimum_cell_voltage", source = 109, target = 109 },
  { name = "maximum_cell_temperature", source = 110, target = 110 },
  { name = "minimum_cell_temperature", source = 111, target = 111 },
  { name = "bams_fault_1", source = 112, target = 112 },             # ! Refer to sheet 3
  { name = "bams_fault_2", source = 113, target = 113 },             # ! Refer to sheet 3
  # * Serial Block 1 Ended
  # * Serial Block 3 Started 
  { name = "ac_line_voltage_l1_to_l2", source = 116, target = 116 },
  { name = "ac_line_voltage_l2_to_l3", source = 117, target = 117 },
  { name = "ac_line_voltage_l3_to_l1", source = 118, target = 118 },
  { name = "ac_l1_current", source = 119, target = 119 },
  { name = "ac_l2_current", source = 120, target = 120 },
  { name = "ac_l3_current", source = 121, target = 121 },
  { name = "ac_frequency", source = 122, target = 122 },
  { name = "total_ac_active_power", source = 135, target = 135 },
  { name = "total_ac_reactive_power", source = 136, target = 136 },
  { name = "total_ac_apparent_power", source = 137, target = 137 },
  { name = "total_ac_pf", source = 138, target = 138 },
  { name = "ac_group_on_off_status", source = 139, target = 139 },
  { name = "ac_group_startup_status", source = 140, target = 140 },
  { name = "pcs_alarm_status", source = 141, target = 141 },
  { name = "ac_bus_over_voltage", source = 143, target = 143 },
  { name = "ac_bus_under_voltage", source = 144, target = 144 },
  { name = "ac_bus_over_frequency", source = 145, target = 145 },
  { name = "ac_bus_under_frequency", source = 146, target = 146 },
  { name = "dc_bus_over_voltage", source = 147, target = 147 },
  { name = "dc_bus_under_voltage", source = 148, target = 148 },
  # * Serial Block 3 Ended

]
holding_registers = [
  # * Serial Block 2 Started
  { name = "bams_contactor_control_1", source = 114, target = 114 },
  { name = "bams_contactor_control_2", source = 115, target = 115 },
  # * Serial Block 2 Ended
  #* Serial Block 6 Started
  { name = "system_main_contactor_control", source = 176, target = 176 },
  { name = "emergency_stop", source = 179, target = 179 },
  { name = "km2", source = 180, target = 180 },
  { name = "km4", source = 181, target = 181 },
  { name = "km5", source = 182, target = 182 },
  #* Serial Block 6 Ended

]
derived_registers = [
  { name = "bams_current_1", target = 106, formula = """
        return |a| {
        let value = convert_u16_to_i16(a);
        value = get_upper_bit_converted_from_s16_u32(value);
        value
      };
        """, input_values = [
    "bams_temporary_current",
  ], bitwise_write = false },
  { name = "bams_current_2", target = 107, formula = """
        return |a| {
        let value = convert_u16_to_i16(a);
        value = get_lower_bit_converted_from_s16_u32(value);
        value
      };
        """, input_values = [
    "bams_temporary_current",
  ], bitwise_write = false },
  { name = "bams_power_1", target = 102, formula = """
        return |a| {
        let value = convert_u16_to_i16(a);
        value = get_upper_bit_converted_from_s16_u32(value);
        value
      };
        """, input_values = [
    "bams_temporary_power",
  ], bitwise_write = false },
  { name = "bams_power_2", target = 103, formula = """
        return |a| {
        let value = convert_u16_to_i16(a);
        value = get_lower_bit_converted_from_s16_u32(value);
        value
      };
        """, input_values = [
    "bams_temporary_power",
  ], bitwise_write = false },
  #* Serial Block 3 Started
  { name = "bams_timedout", target = 1, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l1_ac_active_power", target = 123, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l2_ac_active_power", target = 124, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l3_ac_active_power", target = 125, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l1_ac_reactive_power", target = 126, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l2_ac_reactive_power", target = 127, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l3_ac_reactive_power", target = 128, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l1_ac_apparent_power", target = 129, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l2_ac_apparent_power", target = 130, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l3_ac_apparent_power", target = 131, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l1_ac_pf", target = 132, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l2_ac_pf", target = 133, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "l3_ac_pf", target = 134, reserved = true, input_values = [
  ], bitwise_write = false },

  #* Serial Block 4 Started
  { name = "dc_control_mode", target = 159, reserved = true, input_values = [
  ], bitwise_write = true },
  { name = "dc_current_set_point", target = 160, reserved = true, input_values = [
  ], bitwise_write = true },
  { name = "dc_power_set_point", target = 161, reserved = true, input_values = [
  ], bitwise_write = true },
  #* Serial Block 4 Ended

  #* Serial Block 6 Started
  { name = "system_sub_contactor_control_1", target = 177, reserved = true, input_values = [
  ], bitwise_write = true },
  { name = "system_sub_contactor_control_2", target = 178, reserved = true, input_values = [
  ], bitwise_write = true },
  { name = "micontrol_l1_alarm", target = 190, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "micontrol_l2_alarm", target = 191, reserved = true, input_values = [
  ], bitwise_write = false },
  #* Serial Block 6 Ended

  #* Serial Block 8 (Reserved) Started
  { name = "micontrol_fault", target = 192, reserved = true, input_values = [
  ], bitwise_write = true },
  { name = "fault_reserved_193", target = 193, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_194", target = 194, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_195", target = 195, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_196", target = 196, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_197", target = 197, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_198", target = 198, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_199", target = 199, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_200", target = 200, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_201", target = 201, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_202", target = 202, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_203", target = 203, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_204", target = 204, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_205", target = 205, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_206", target = 206, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_207", target = 207, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_208", target = 208, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_209", target = 209, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_210", target = 210, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_211", target = 211, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_212", target = 212, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_213", target = 213, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_214", target = 214, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "fault_reserved_215", target = 215, reserved = true, input_values = [
  ], bitwise_write = false },
  #* Serial Block 8 (Reserved) Ended
]


[[inputs.tcp]]
name = "PCS"
controller = "192.168.2.73:503"
slave_id = 1
input_registers = [
  # * Serial Block 7 Started
  { name = "pcs_system_status", source = 183, target = 183 },                      #! Refer to sheet 3
  { name = "pcs_ac_group_status", source = 184, target = 184 },                    #! Refer to sheet 3
  { name = "pcs_dc_group_status", source = 185, target = 185 },                    #! Refer to sheet 3
  { name = "pcs_ac_accumulative_charge_energy_1", source = 186, target = 186 },
  { name = "pcs_ac_accumulative_charge_energy_2", source = 187, target = 187 },
  { name = "pcs_ac_accumulative_discharge_energy_1", source = 188, target = 188 },
  { name = "pcs_ac_accumulative_discharge_energy_1", source = 189, target = 189 },
  # * Serial Block 7 Ended

]
holding_registers = [

  # * Serial Block 4 Started
  { name = "grid_interconnection_mode", source = 149, target = 149 },
  { name = "energy_dispatching_mode", source = 150, target = 150 },
  { name = "pf_setpoint", source = 151, target = 151 },
  { name = "active_power_control_mode", source = 152, target = 152 },
  { name = "active_power_setpoint", source = 153, target = 153 },
  { name = "reactive_power_setpoint", source = 154, target = 154 },
  { name = "maximum_charge_current", source = 155, target = 155 },
  { name = "minimum_discharge_current", source = 156, target = 156 },
  { name = "dc_output_voltage", source = 157, target = 157 },
  { name = "dc_maximum)output_voltage", source = 158, target = 158 },
  { name = "grid_reconnecion_upper_limit_volt", source = 162, target = 162 },
  { name = "grid_reconnection_lower_limit_volt", source = 163, target = 163 },
  { name = "grid_reconnecion_upper_limit_freq", source = 164, target = 164 },
  { name = "grid_reconnection_lower_limit_freq", source = 165, target = 165 },
  { name = "pcs_start", source = 166, target = 166, min = 0, max = 1 },
  { name = "pcs_stop", source = 167, target = 167 },
  { name = "pcs_clear_fault", source = 168, target = 168 },

]
derived_registers = [
  #* Serial Block 3 Started
  { name = "pcs_timedout", target = 2, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "pcs_fault_status", target = 142, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = 1
        }
        value
      };
        """, input_values = [
    "pcs_clear_fault",
  ], bitwise_write = false }, # TODO: Add all the fault input values for calculation
]


[[inputs.tcp]]
name = "HVAC"
controller = "192.168.2.73:503"
slave_id = 1
input_registers = [
  # * Cabinet 1 Input Block Start
  { name = "1_hvac_running_status", source = 216, target = 216 },
  { name = "1_compressor_status", source = 217, target = 217 },
  { name = "1_heater_status", source = 218, target = 218 },
  { name = "1_compressor_failure_alarm", source = 219, target = 219 },
  { name = "1_heater_failure_alarm", source = 220, target = 220 },
  { name = "1_ambient_temperature", source = 225, target = 225 },
  { name = "1_ambient_humidity", source = 226, target = 226 },
  { name = "1_door_sensor_status", source = 227, target = 227 },
  { name = "1_smoke_detection_status", source = 228, target = 228 },
  { name = "1_flooding_status", source = 229, target = 229 },
  # * Cabinet 1 Input Block End
]
holding_registers = [
  # * Cabinet 1 Holding Block Start
  { name = "1_cooling_start_temperature", source = 221, target = 221 },
  { name = "1_cooling_temperature_band", source = 222, target = 222 },
  { name = "1_heating_start_temperature", source = 223, target = 223 },
  { name = "1_heating_temperature_band", source = 224, target = 224 },
  { name = "1_cabinet_fan_control", source = 230, target = 230 },
  { name = "green_light", source = 212, target = 900 },
  { name = "yellow_light", source = 213, target = 901 },
  { name = "red_light", source = 214, target = 902 },
  { name = "alarm_sound", source = 215, target = 903 },
  # * Cabinet 1 Holding Block End
]
derived_registers = [
  { name = "env_timedout", target = 3, reserved = true, input_values = [
  ], bitwise_write = false },
  # * Cabinet 1 Reserved Block Start
  { name = "cabinet_1_reserved_231", target = 231, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "cabinet_1_reserved_232", target = 232, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "cabinet_1_reserved_233", target = 233, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "cabinet_1_reserved_234", target = 234, reserved = true, input_values = [
  ], bitwise_write = false },
  { name = "cabinet_1_reserved_235", target = 235, reserved = true, input_values = [
  ], bitwise_write = false },
  # * Cabinet 1 Reserved Block End

  #* Group 5 Block Start
  { name = "ambient_temperature_fault", target = 169, formula = """
        return |a| {
        let value = 0;
        if a > 39 || a < 10{
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_ambient_temperature",
  ] },
  { name = "ambient_humidity_fault", target = 170, formula = """
        return |a| {
        let value = 0;
        if a > 60{
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_ambient_humidity",
  ] },
  { name = "smoke_sensor_status", target = 171, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_smoke_detection_status",
  ] },
  { name = "door_sensor_status", target = 172, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_door_sensor_status",
  ] },
  { name = "flooding_sensor_status", target = 173, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_flooding_status",
  ] },
  #* Group 5 Block End
  #* Group 6 Cabinet Block Start
  { name = "air_condition_status", target = 174, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_hvac_running_status",
  ], bitwise_write = true },
  { name = "cabinet_fan_status", target = 175, formula = """
        return |a| {
        let value = 0;
        if a == 1 {
          value = set_bit(value, 0);
        }
        value
      };
        """, input_values = [
    "1_cabinet_fan_control",
  ], bitwise_write = true },
  #* Group 6 Cabinet Block Start
]
